spring:
  application:
    name: pos-carts
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}