spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: pos-carts-route
          uri: lb://pos-carts
          predicates:
            - Path=/api/cart/**
        - id: pos-products-route
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**
        - id: pos-counter-route
          uri: lb://pos-counter
          predicates:
            - Path=/api/counter/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    pos-carts-cb:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
    pos-products-cb:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
    pos-counter-cb:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s